services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80" # Expose port 8080 for frontend
    depends_on:
      - backend
      - backend2 

  backend:
    build: .
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80" # Expose port 80 for backend
    depends_on:
      - db

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend2
    volumes:
      - ./backend2:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db2

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  db2:
    # Nouvelle base de données ajoutée
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker2
      - MYSQL_USER=php_docker2
      - MYSQL_PASSWORD=password2
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db2:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db2
      - PMA_PORT=3306

networks:
  default:
    name: my_network
